--ENTIDADE ALUNO -----------------------------------------------------------

--RETORNA AS UCS DO ALUNO SELECIONADO               TODO:RELATORIO
CREATE FUNCTION [SAA].[UCS_DO_ALUNO] (@NMEC int) RETURNS TABLE
AS
	RETURN(
		SELECT  Nome, NMEC, Email, SAA.ALUNO.ID_Curso, ID_UC
		FROM SAA.Relacao_UC_CURSO JOIN SAA.ALUNO ON SAA.Relacao_UC_CURSO.ID_Curso=SAA.ALUNO.ID_Curso
		WHERE NMEC = @NMEC
	)



--ENTIDADE REGISTO -------------------------------------------------------------

--Function que retorna uma lista com os registos de um certo aluno.
CREATE FUNCTION SAA.REGISTOS_DO_NMEC (@NMEC INT) RETURNS TABLE
AS
	RETURN (
		SELECT *
		FROM SAA.REGISTO
		WHERE NMEC = @NMEC
		)

--VER ALUNOS DE UM DEPARTAMETNO
CREATE FUNCTION [SAA].[ALUNO_DE_DEPARTAMENTO] (@Nome_Dep VARCHAR(50)) RETURNS TABLE
AS
	RETURN (
		SELECT Nome, NMEC, SAA.ALUNO.ID_Curso, Email, ID_Horario
		FROM (SAA.ALUNO JOIN SAA.CURSO ON SAA.ALUNO.ID_CURSO=SAA.CURSO.ID_CURSO) JOIN SAA.DEPARTAMENTO ON SAA.CURSO.ID_Dep=SAA.DEPARTAMENTO.ID_Dep
		WHERE Nome_Dep = @Nome_Dep
		)
GO

--VER ALUNOS DE UM CURSO
CREATE FUNCTION [SAA].[ALUNOS_DO_CURSO_UDF] (@NOME_CURSO VARCHAR(20)) RETURNS TABLE
AS
	RETURN (
		SELECT Nome, NMEC, Email, RegimeEstudo, ID_Horario, ID_Biblioteca, SAA.ALUNO.ID_Curso, NMEC_Tutor, Idade
		FROM SAA.ALUNO JOIN SAA.CURSO ON SAA.ALUNO.ID_Curso=SAA.CURSO.ID_Curso
		WHERE Nome_Curso = @NOME_CURSO
		)
GO

--VER ALUNOS DA TURMA
CREATE FUNCTION [SAA].[ALUNOS_DA_TURMA_UDF] (@ID_TURMA INT) RETURNS TABLE
AS
	RETURN (
		SELECT Nome, SAA.ALUNO.NMEC, Email, RegimeEstudo, ID_Horario, ID_Biblioteca, SAA.ALUNO.ID_Curso, NMEC_Tutor, Idade
		FROM SAA.Relacao_ALUNO_TURMA JOIN SAA.ALUNO ON SAA.ALUNO.NMEC = SAA.Relacao_ALUNO_TURMA.NMEC
		WHERE ID_Turma = @ID_TURMA
	)
GO

--Function usada no trigger de adicionar registo para verificar se a UC do registo pertence ao curso do aluno.
CREATE FUNCTION [SAA].[X_UC_DO_ALUNO_X] (@NMEC int, @ID_UC INT) RETURNS TABLE
AS
	RETURN(
		SELECT  NMEC , ID_UC
		FROM SAA.Relacao_UC_CURSO JOIN SAA.ALUNO ON SAA.Relacao_UC_CURSO.ID_Curso=SAA.ALUNO.ID_Curso
		WHERE NMEC = @NMEC AND ID_UC = @ID_UC
	)
GO

